name: "Push notification on Whatsapp"
description: "Triggers a Private Message to the specified Whatsapp user when code is pushed in the master branch"
author: "Ishween Kaur"
branding:
  icon: message-square
  color: blue


runs:
  using: "docker"
  image: "Dockerfile"
